Repository RPGDM/RPGPlatformer, pull requests merged in 2022-04, with the labels that each got.

#2 Feature/RPGMD-5-create-terrain
  Assets/Scenes/SampleScene.unity
  ProjectSettings/TagManager.asset
Labels: feature

#4 Create LICENSE
  LICENSE
Labels: documentation

#5 added loot souls
  Assets/MyMaterial/soul.physicsMaterial2D
  Assets/MyMaterial/soul.physicsMaterial2D.meta
  Assets/Prefabs/Enemies/rat-black.prefab
  Assets/Prefabs/Soul.prefab
  Assets/Prefabs/Soul.prefab.meta
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Enemy.cs
  Assets/Scripts/HeroScripts/CombatScript.cs
  Assets/Scripts/HeroScripts/MovingScript.cs
  Assets/Scripts/HeroScripts/Player.cs
  Assets/Scripts/HeroScripts/SoulsController.cs
  Assets/Scripts/HeroScripts/SoulsController.cs.meta
  Assets/Scripts/Soul.cs
  Assets/Scripts/Soul.cs.meta
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: feature

#7 Feature/rpgmd 10 circle ci integration
  .circleci/config.yml
Labels: enhancement, feature

#8 Feature/rpgmd 12 enemy combat
  Assets/AllAssets/Hero Knight - Pixel Art/Environment/Walls_noFriction.physicsMaterial2D
  Assets/Animations/EnemyAnimations/rat-black.controller
  Assets/Animations/MainHeroAnimations/MainHero.controller
  Assets/Animations/MainHeroAnimations/TakeDamage.anim
  Assets/Animations/MainHeroAnimations/TakeDamage.anim.meta
  Assets/Prefabs/Enemies/rat-black.prefab
  Assets/Scenes/TestScene.unity
  Assets/Scripts/Enemy.cs
  Assets/Scripts/Enemy.meta
  Assets/Scripts/Enemy/Enemy.cs
  Assets/Scripts/Enemy/Enemy.cs.meta
  Assets/Scripts/Enemy/EnemyMovement.cs
  Assets/Scripts/Enemy/EnemyMovement.cs.meta
  Assets/Scripts/HeroScripts/CombatScript.cs
  Assets/Scripts/HeroScripts/MovingScript.cs
  Assets/Scripts/HeroScripts/Player.cs
Labels: invalid
